config/routes.rb
Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :profiles, only: %i[index update], path: :profile
  resources :posts, only: %i[new show create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :articles
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :reactable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  enum state: {draft: 0, in_review: 1, rejected: 2, approved: 3, published: 4, archived: 5}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/create.html.slim
h1 Articles#create
p Find me in app/views/articles/create.html.slim

app/views/articles/destroy.html.slim
h1 Articles#destroy
p Find me in app/views/articles/destroy.html.slim

app/views/articles/index.html.slim
= turbo_stream_from  :comments
.container.mx-auto.mt-16.px-5.py-5.flex.rounded-lg
  .grid.grid-cols-5.gap-16.w-full
    .order-2.lg:order-1.flex-col.col-span-5.lg:col-span-3
      .flex.justify-between
        h2.text-xl.font-bold.mb-5 Artículos
      - if Current.user
        = turbo_frame_tag Article.new
          .mb-4.text-right = link_to '+ Nuevo', new_article_path, class: 'bg-blue-500 text-white font-bold rounded-lg px-2 py-2 text-sm shadow'
      - else
        .mb-4.text-right = link_to '+ Nuevo', sign_up_path, data: { turbo: false }, class: 'bg-blue-500 text-white font-bold rounded-lg px-2 py-2 text-sm shadow'

      = turbo_frame_tag 'feed'
        div.flex.flex-col.gap-24
          - @articles.each do |article|
            = turbo_frame_tag article
              = render(Articles::ArticleComponent.new(title: article.title, content_text: article.content, user: article.user))
          - unless Current.user
            = render(Shared::RegistrationInvitationComponent.new())

app/views/articles/show.html.slim
h1 Articles#show
p Find me in app/views/articles/show.html.slim

app/views/articles/update.html.slim
h1 Articles#update
p Find me in app/views/articles/update.html.slim