config/routes.rb
Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :profiles, only: %i[index update], path: :profile
  resources :posts, only: %i[new show create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :articles
end

app/views/shared/_header.html.slim
.flex.justify-between.py-4.px-2.shadow-lg.dark:bg-gray-900.dark:text-white
  .font-bold.text-xl
    = link_to 'Adventista App', root_path
  .flex.gap-4
    = render(Shared::SelectLangComponent.new(current: I18n.locale,
                                             available_locales: I18n.available_locales)) unless Current.user
    - if Current.user.present?
      = link_to Current.user.username, profiles_path,  class: 'font-light'

      / div
      /   = link_to "Change email address", edit_identity_email_path

      / div
      /   = link_to "Change password", edit_password_path

      / div
      /   = link_to "Devices & Sessions", sessions_path

      = button_to t('actions.logout'), Current.session, method: :delete, class: 'text-xs text-white bg-red-500 px-2 py-0.5 rounded'
    - else
      .flex.gap-3.items-center
        = link_to t('actions.login'), sign_in_path, class: 'px-2 py-1 rounded bg-white shadow border border-gray-600 dark:bg-gray-800 dark:text-white'
        | ó
        = link_to t('actions.register_me'), sign_up_path, class: 'px-2 py-1 rounded bg-lime-400 shadow  border font-bold bg-gradient-to-r from-emerald-600 to-lime-500 dark:border-gray-500'