config/routes.rb
Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :profiles, only: %i[index update], path: :profile
  resources :posts, only: %i[new show create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :articles
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate, only: :index

  def index
    @pagy, @posts = pagy(Post.includes(:comments, :likes, user: :profile).all.order(created_at: :desc))
  end
end

app/views/home/index.html.slim
= turbo_stream_from  :comments
.container.mx-auto.mt-28.px-5.py-5.flex.rounded-lg
  .grid.grid-cols-5.gap-16.w-full
    .order-2.lg:order-1.flex-col.col-span-5.lg:col-span-3
      .flex.justify-between
        h2.text-xl.font-bold.mb-5 Publicaciones
      - if Current.user
        = turbo_frame_tag Post.new
          .mb-4.text-right = link_to '+ Nuevo', new_post_path, class: 'bg-blue-500 text-white font-bold rounded-lg px-2 py-2 text-sm shadow'
      - else
        .mb-4.text-right = link_to '+ Nuevo', sign_up_path, data: { turbo: false }, class: 'bg-blue-500 text-white font-bold rounded-lg px-2 py-2 text-sm shadow'

      = turbo_frame_tag 'feed'
        - @posts.each do |post|
          = turbo_frame_tag post
            = render(Posts::PostComponent.new(post:))
        - unless Current.user
          = render(Shared::RegistrationInvitationComponent.new())
    .order-1.lg:order-2.col-span-5.lg:col-span-2.flex-col.grid-cols-2
      h2.block.text-xl.font-bold.mb-2 Noticias
      .flex.justify-between.items-center.mb-4.gap-4.mb-5
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://cdn.shopify.com/s/files/1/0231/8024/7118/files/SHOPIFY_Home_Page_Banners_3_e8eee1f4-cfc7-46ec-afcb-ad8925f4c58a_1920x.png?v=1679922931')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Lorem ipsum, dolor sit amet consectetur adipisicing. Dolore...
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://cdn.shopify.com/s/files/1/0231/8024/7118/files/SHOPIFY_Home_Page_Banners_3_e8eee1f4-cfc7-46ec-afcb-ad8925f4c58a_1920x.png?v=1679922931')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Lorem ipsum, dolor sit amet consectetur mas otro
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://cdn.shopify.com/s/files/1/0231/8024/7118/files/SHOPIFY_Home_Page_Banners_3_e8eee1f4-cfc7-46ec-afcb-ad8925f4c58a_1920x.png?v=1679922931')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Sit amet adipisicing elit. Dolore amigos
        .grow.news-more.text-sm Ver más

      h2.block.text-xl.font-bold.mb-2 Articulos
      .flex.justify-between.items-center.mb-4.gap-4.mb-5
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/09/WEB3-CROSS-SUNRISE-SUN-RAY-LIGHT-JESUS-shutterstock_366834113.jpg?w=620&h=310&crop=1')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Como lograr una mejor cosecha
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/09/WEB3-CROSS-SUNRISE-SUN-RAY-LIGHT-JESUS-shutterstock_366834113.jpg?w=620&h=310&crop=1')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Cuidado con la modernidad
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/09/WEB3-CROSS-SUNRISE-SUN-RAY-LIGHT-JESUS-shutterstock_366834113.jpg?w=620&h=310&crop=1')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 DIY, gran idea para departamento de infantes
        .grow.news-more.text-sm Ver más

      h2.text-xl.font-bold.mb-2 Recetas
      .flex.justify-between.items-center.mb-4.gap-4.mb-5
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://images.immediate.co.uk/production/volatile/sites/30/2018/06/Vegan-salad-bowl-499145d.jpg?quality=90&resize=556,505')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Macarrones saludables!
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://images.immediate.co.uk/production/volatile/sites/30/2018/06/Vegan-salad-bowl-499145d.jpg?quality=90&resize=556,505')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Ceviche vegano
        .new.flex.flex-col.justify-end.bg-gray-400.h-28.w-full.rounded.bg-cover.overflow-hidden style="background-image: url('https://images.immediate.co.uk/production/volatile/sites/30/2018/06/Vegan-salad-bowl-499145d.jpg?quality=90&resize=556,505')"
          .text-xs.font-semibold.px-2.py-1.bg-black.opacity-70 Leche de soja, paso a paso
        .grow.news-more.text-sm Ver más

      h2.hidden.text-xl.font-bold.mb-5 Musica :D
      .w-full.flex.justify-between.mb-4.gap-5