config/routes.rb
Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :profiles, only: %i[index update], path: :profile
  resources :posts, only: %i[new show create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :articles
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  def index
    @available_locales = I18n.available_locales
    @locale = Current.user.locale
  end

  def update
    user = Current.user
    user.settings = settings_params
    user.save

    redirect_to settings_url, notice: t('.updated_success')
  end

  private

  def settings_params
    params.require(:settings).permit(:locale)
  end
end

app/views/settings/index.html.slim
.container.rounded-lg.bg-white.shadow-2xl.p-10.flex.flex-col.w-96.mx-auto.my-24.border.dark:bg-gray-800.dark:text-white.dark:border-gray-600.container.rounded-lg.bg-white.shadow-2xl.p-10.flex.flex-col.w-96.mx-auto.my-24.border
  - if notice
    .mb-4.bg-green-200.text-green-600.border.border-green-400.rounded.py-1.px-2 style="color: green" = notice

  h1.text-center.font-bold.text-2xl.mb-5 = t('.title')
  = form_with scope: :settings, model: Current.user, url: update_settings_url do |f|
    = f.label :locale
    = f.select :locale, @available_locales, {}, class: 'select block'

    = f.submit t('actions.save'), class: 'btn-primary block w-full mt-5'
  = link_to t('actions.go_back'), profiles_url, class: 'btn-secondary'